name: Arcade-Rust Docker 1.85.1 slim-bookworm CI

on:
  push:
    branches: [master]
    paths:
      - arcade/rust/1.85.1-slim-bookworm/**
      - .github/workflows/arcade-rust-1.85.1-slim-bookworm.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Build and Push to Dockerhub
      uses: docker/build-push-action@v3
      with:
        push: true
        context: arcade/rust/1.85.1-slim-bookworm
        tags: heybit/arcade-rust:1.85.1-slim-bookworm
        platforms: linux/amd64