name: Arcade-Rust Docker 1.70.0 slim-bullseye CI

on:
  push:
    branches: [master]
    paths:
      - arcade/rust/1.70.0-slim-bullseye/**
      - .github/workflows/arcade-rust-1.70.0-slim-bullseye.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Build and Push to Dockerhub
      uses: docker/build-push-action@v3
      with:
        push: true
        context: arcade/rust/1.70.0-slim-bullseye
        tags: heybit/arcade-rust:1.70.0-slim-bullseye
        platforms: linux/amd64