name: Arcade-Rust 1.63 alpine Docker CI

on:
  push:
    branches: [master]
    paths:
      - arcade/rust/1.63-alpine/**
      - .github/workflows/arcade-rust-1.63-alpine.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push to Github Package
        uses: docker/build-push-action@v2
        with:
          push: true
          context: arcade/rust/1.63-alpine
          tags: heybit/arcade-rust:1.63-alpine
