name: Arcade Python 3.11.8-slim-bookworm Docker CI

on:
  push:
    branches: [ master ]
    paths:
      - arcade/python/3.11.8-slim-bookworm/**
      - .github/workflows/arcade-python3.11.8-slim-bookworm.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Build and Push to Dockerhub
      uses: docker/build-push-action@v5
      with:
        context: arcade/python/3.11.8-slim-bookworm
        push: true
        tags: heybit/arcade-python:3.11.8-slim-bookworm
        platforms: linux/amd64,linux/arm64