name: Arcade-Python Docker CI

on:
  push:
    branches: [master]
    paths:
      - arcade/python/3.8.14/**
      - .github/workflows/arcade-python.yml
  workflow_dispatch:

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push to Github Package
        uses: docker/build-push-action@v2
        with:
          push: true
          context: arcade/python/3.8.14
          tags: heybit/arcade-python:3.8.14
