name: Arcade Serverless with python 3.11.0 Docker CI

on:
  push:
    branches: [ master ]
    paths:
      - arcade/serverless/python-3.11.0-slim-bullseye/**
      - .github/workflows/arcade-serverless-python-3.11.0.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Build and Push to Dockerhub
      uses: docker/build-push-action@v3
      with:
        context: arcade/serverless/python-3.11.0-slim-bullseye
        push: true
        tags: heybit/arcade-serverless:3.11.0-slim-bullseye