name: Arcade Nodejs 20.11.0-alpine Docker CI

on:
  push:
    branches: [ master ]
    paths:
      - arcade/nodejs/20.11.0-alpine/**
      - .github/workflows/arcade-nodejs-20.11.0-alpine.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Build and Push to Dockerhub
      uses: docker/build-push-action@v5
      with:
        context: arcade/nodejs/20.11.0-alpine
        push: true
        tags: heybit/arcade-nodejs:20.11.0-alpine