name: Arcade Nodejs 18.12.1-alpine Docker CI

on:
  push:
    branches: [ master ]
    paths:
      - arcade/nodejs/18.12.1-alpine/**
      - .github/workflows/arcade-nodejs-18.12.1-alpine.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Build and Push to Dockerhub
      uses: docker/build-push-action@v3
      with:
        context: arcade/nodejs/18.12.1-alpine
        push: true
        tags: heybit/arcade-nodejs:18.12.1-alpine