name: Node18 Docker CI(pnpm)
on:
  push:
    branches: [ master ]
    paths:
      - node18-pnpm/**
      - .github/workflows/node18-pnpm.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Push to Dockerhub
      uses: docker/build-push-action@v1
      with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: heybit/node18-pnpm
          tags: latest
          tag_with_sha: true
          path: node18-pnpm
          