name: Python 3.8.11 Docker CI

on:
  push:
    branches: [ master ]
    paths:
      - python3.8.11/**
      - .github/workflows/python3.8.11.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v2
    - name: Push to Dockerhub
      uses: docker/build-push-action@v1
      with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: heybit/python
          tags: 3.8.11
          tag_with_sha: true
          path: python3.8.11
