name: Python 3.11.0-alpine Docker CI

on:
  push:
    branches: [ master ]
    paths:
      - python3.11.0-alpine/**
      - .github/workflows/python3.11.0-alpine.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
    - name: Push to Dockerhub
      uses: docker/build-push-action@v3
      with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          repository: heybit/python
          tags: 3.11.0-alpine
          tag_with_sha: true
          path: python3.11.0-alpine