name: Service Nodejs 20.18.3-slim Docker CI

on:
  push:
    branches: [ master ]
    paths:
      - service/nodejs/20.18.3-slim/**
      - .github/workflows/service-nodejs-20.18.3-slim.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    - name: Build and Push to Dockerhub
      uses: docker/build-push-action@v5
      with:
        context: service/nodejs/20.18.3-slim
        push: true
        tags: heybit/service-nodejs:20.18.3-slim
